global:
  region: us-east-1
  release: develop
  sync_base: ./
  sync_dirs: [
    '*'
  
  ]
  sync_exclude: [
    '.swp',
    '.git',
    '.swo'
  ]
  sync_dest_bucket: aws-practice-us-east-1
  tags:
    Project: AWS-Practice
    Environment: Dev
    Release : develop
  parameters:
    Project: AWS-Practice
    Environment: Dev
    CloudToolsBucket: aws-practice-us-east-1
