global:
  region: us-east-1
  sync_base: ./
  sync_dirs: [
    'cloudformation'
  
  ]
  sync_exclude: [
    '.swp',
    '.git',
    '.swo'
  ]
  sync_dest_bucket: aws-practice-us-east-1
  tags:
    Project: AWS-Practice
    Environment: Dev
  parameters:
    Project: AWS-Practice
    Environment: Dev
    CloudToolsBucket: aws-practice-us-east-1

Main:
  stack_name: Main
  CloudToolsBucket: aws-practice-us-east-1
  template: ./cloudformation/top.yaml
  parameters:
    Environment: Dev
    CloudToolsBucket: aws-practice-us-east-1
