AWSTemplateFormatVersion: 2010-09-09
Description: Stack to create kubernetes control plane

Parameters:
  EnvironmentName:
    Type: String
    Description: Name of the environment to use in naming.
  ClusterName:
    Type: String
    Description: Name of the Kubernetes cluster
  VPC:
    Type: String
    Description: VPC that resources will belong too
  SecurityGroup:
    Type: String
    Description: Security Group to place instances into
  PublicSubnet1:
    Type: String
    Description: Public subnet in the vpc
  PublicSubnet2:
    Type: String
    Description: Private subnet in the vpc
  EksRole:
    Type: String
    Description: Arn of eks cluster role

Resources:
  Cluster:
    Type: AWS::EKS::Cluster
    Properties: 
      KubernetesNetworkConfig: 
        ServiceIpv4Cidr: 10.0.0.0/12 #netmask must be between /12 and /24
      Name: !Ref ClusterName
      ResourcesVpcConfig: 
        SecurityGroupIds: 
          - !Ref SecurityGroup
        SubnetIds: #Cluster must be in at least 2 AZs
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
      RoleArn: !Ref EksRole


